[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --class=AdminUserSeeder --force && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "never"